version: 2.1

# Defining the jobs for this project.
jobs:
  build:
    docker:
      - image: vpindelski/simple:latest
    steps:
      - run: echo "This is the build job."
  test:
    docker:
      - image: vpindelski/simple:latest
    steps:
      - run: echo "This is the test job."

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build